r"""kyp-model.ai — the copy of record (START_ME_UP\kyp-model-ai.md, CEO-signed) carried verbatim into the Worker as CM-KG\ESTATE\worker\kyp-copy.js.
Never edits copy: title, meta, H1, reason for being, sections 1–5, byline and the link map are read as written. Re-run when the md changes."""
import json, re
SRC = r'C:\ALLOOLOO\START_ME_UP\kyp-model-ai.md'; OUT = r'C:\ALLOOLOO\CM-KG\ESTATE\worker\kyp-copy.js'
md = open(SRC, encoding='utf-8').read()
blocks = re.split(r'\n## ', md)
head = blocks[0]
sec = {}
for b in blocks[1:]:
    name, _, body = b.partition('\n'); sec[name.strip()] = body.strip()
def clauses(text):
    out = []
    for line in text.splitlines():
        m = re.match(r'^(\d+\.\d+)\s+(.*)$', line.strip())
        if m: out.append([m.group(1), m.group(2)])
        elif line.strip(): out.append(['', line.strip()])
    return out
sections = []
for k, v in sec.items():
    m = re.match(r'^(\d)\s+(.*)$', k)
    if m: sections.append({'n': m.group(1), 'title': m.group(2), 'clauses': clauses(v)})
links = []
for line in sec.get('Live links (item 3 of the order)', '').splitlines():
    if '→' in line:
        a, b = line.split('→', 1); url = b.strip().split(' ')[0]; note = b.strip()[len(url):].strip(' ()'); links.append([a.strip(), url] + ([note] if note else []))
copy = {'source': 'START_ME_UP/kyp-model-ai.md', 'signed': re.search(r'CEO-signed · ([^·]+) ·', head).group(1).strip() if re.search(r'CEO-signed · ([^·]+) ·', head) else '', 'title': sec['title'], 'meta': sec['meta'], 'h1': sec['H1'], 'reason': sec['Reason for being'], 'sections': sections, 'byline': sec['Byline'], 'links': links}
open(OUT, 'w', encoding='utf-8').write('// GENERATED by RAILS/kyp_copy.py from START_ME_UP/kyp-model-ai.md — the CEO-signed copy of record, verbatim. Do not edit here.\nexport default ' + json.dumps(copy, ensure_ascii=False, indent=1) + ';\n')
print('kyp-copy.js:', len(sections), 'sections,', sum(len(s['clauses']) for s in sections), 'clauses,', len(links), 'links; title:', copy['title'][:60])
