// ORDER-019 node surfaces — per-node inputs (NODE-SURFACES.md §7). Sections 4, 5, 6 carry the node's rail README facts; Gaps notes verbatim.
// Counts and dates are never typed here: the Worker fills {{issuers}}, {{events}}, {{drop}} from list_nodes on every render.
export default {
  ca: {
    country: 'Canada', region: 'Canada Central', city: 'Toronto', spelling: 'ca',
    title: 'Canada Capital Markets Knowledge Graph — ca-cm-kg',
    meta: 'Agentic record of {{issuers}} Canadian issuers across TSX, TSX Venture, CSE and Cboe Canada, with {{events}} dated disclosure events; sourced, read-dated, served from Toronto over MCP and A2A.',
    h1: 'Four Canadian exchanges, one record per listed company, callable by an agent.',
    reason: 'Canada lists on four venues and this node carries all four: Toronto Stock Exchange, TSX Venture Exchange, the Canadian Securities Exchange and Cboe Canada, {{issuers}} issuer records with {{events}} dated disclosure events behind them. Identity comes from the exchange lists and GLEIF; the disclosure trail comes from the wires, exchange bulletins and SEDAR+ links per issuer. Insiders, auditors and transfer agents are read from the issuer profile and the filings named on it, each with the URL it was read from and the day it was read. The record is served from Canada Central and the apex router only forwards to it. Dual-listed names resolve here and on the node of the other listing. What could not be read stays blank and is listed in the Known gaps clause.',
    coverage: 'Toronto Stock Exchange (TSX); TSX Venture Exchange (TSXV); Canadian Securities Exchange (CSE); Cboe Canada',
    sources: 'TSX and TSXV issuer lists (TMX); CSE listed-companies API; Cboe Canada listings API; GLEIF (LEI records, ISIN-to-LEI mapping); SEDAR+ filing links per issuer; newswires (Canada Newswire, GlobeNewswire, Business Wire)',
    mapping: 'identity (name, ticker, exchange, ISIN) ← exchange lists; LEI, legal jurisdiction, other names ← GLEIF; auditor, transfer agent ← issuer profile and annual filing pages (Tavily-read, then Perplexity-grounded); disclosure events ← wire releases and exchange bulletins matched under the name rule',
    gaps: 'Incorporation jurisdiction comes from the GLEIF legal-jurisdiction field only (label GLEIF LEI record …); the statute-phrase read from filings is retired. Rows without an LEI record carry a blank jurisdiction and a Gaps line. SEDI and SEDAR+ refuse machines (HTTP 403); filing links are carried, not read.',
    gapsFrom: 'ca-width0 README, build notes and Sources table',
    tiers: 'TSX (senior); TSXV (venture, Tier 1 and Tier 2); CSE; Cboe Canada (including Canadian Depositary Receipts, which resolve to the foreign issuer\'s home node as well).',
    language: 'English; French where the issuer files in French. Titles carried as published.',
    regulator: 'Provincial securities commissions under the Canadian Securities Administrators (Ontario Securities Commission for TSX-listed issuers). Exchange operators: TMX Group; CSE; Cboe Canada.',
    register: 'Corporations Canada (federal) or the provincial registry named by the incorporating statute. Register key: corporation number as carried on the GLEIF record.',
    channel: 'SEDAR+ (filings); newswires; exchange bulletins (TSX, TSXV, CSE).',
    fiscal: 'set per issuer; carried as filed.',
    idForms: ['TSX:SHOP', 'SHOP.TO', 'TSXV:<code>', 'CSE:<code>', 'CBOE-CANADA:<code>', 'ISIN (CA…)', 'LEI', 'legal name', 'sourced alias'],
    auditorLine: 'Auditor and transfer agent: read from the issuer profile and annual filing pages, named to a closed list; unrecognised names go to Gaps.',
    example: 'TSX:SHOP', duty: 'KYP (Know Your Product)'
  },
  us: {
    country: 'United States', region: 'East US', city: 'Virginia', spelling: 'us',
    title: 'United States Capital Markets Knowledge Graph — us-cm-kg',
    meta: 'Agentic record of {{issuers}} US-listed issuers on NYSE, Nasdaq and Cboe, {{events}} dated filings from EDGAR; every field sourced and read-dated; served from East US over MCP and A2A.',
    h1: 'Every SEC-registered issuer on NYSE, Nasdaq and Cboe, from EDGAR, as a callable record.',
    reason: 'This node is built from EDGAR alone: the SEC list of exchange-listed filers, the submissions header per CIK, the filings index and the annual report cover page. {{issuers}} issuer records, {{events}} dated filing events — every 10-K, 10-Q, 8-K, proxy, registration statement and ownership form of the trailing twelve months, typed by form and by 8-K item. Auditor name, location and firm ID are the inline XBRL facts on the 10-K cover; the transfer agent is read from the 10-K text and labelled as read. LEI and ISIN come from the GLEIF golden copy joined on the exact legal name and US jurisdiction; nothing is derived. The pull runs inside East US under a declared User-Agent and writes to the East US store, which is the only place the record body is held. Blank fields are blank because EDGAR does not carry them.',
    coverage: 'New York Stock Exchange (NYSE); Nasdaq; Cboe US equities (per the SEC exchange field)',
    sources: 'EDGAR company_tickers_exchange.json; EDGAR submissions API per CIK; EDGAR filings index and 10-K inline XBRL cover facts (dei:AuditorName, dei:AuditorLocation, dei:AuditorFirmId, dei:DocumentPeriodEndDate); GLEIF golden copy (LEI records) and ISIN-to-LEI mapping',
    mapping: 'identity (name as filed, ticker, exchange, SIC, state of incorporation, fiscal year end, filer category, addresses, former names) ← EDGAR submissions header; LEI, registration status, other names ← GLEIF golden copy; ISIN ← GLEIF mapping file; auditor, period end ← 10-K cover inline XBRL; transfer agent ← 10-K text windows read by Gemini; disclosure events ← EDGAR filings index',
    gaps: 'No dei:AuditorName tag on the latest annual report cover for foreign private issuers (20-F, 40-F) and for older filings — auditor stays blank with the note carried on the field. Several US ISINs on one LEI leave the ISIN blank with the list in the note. Issuers whose exact legal name is not on a GLEIF record in a US jurisdiction carry no LEI. Multiple share classes resolve as separate tickers on one CIK.',
    gapsFrom: 'us-job README and the notes carried on the rendered fields',
    tiers: 'NYSE; Nasdaq (Global Select, Global Market, Capital Market — tier not carried by the SEC list, so not stated); Cboe. Security type by SIC and name: corporate, fund or trust (SIC 6722/6726 or fund words), SPAC (SIC 6770).',
    language: 'English.',
    regulator: 'U.S. Securities and Exchange Commission. Exchange operators: Intercontinental Exchange (NYSE); Nasdaq, Inc.; Cboe Global Markets.',
    register: 'State of incorporation as filed on the submissions header (rendered as United States — <state>); no federal corporate register. Register key: CIK (SEC Central Index Key) and EIN as filed.',
    channel: 'EDGAR (all forms); 8-K items typed: 2.02 results, 5.02 director change, 1.01/7.01/8.01 corporate news, 5.07 meeting, 3.01 halt or delisting notice, 2.01 acquisition.',
    fiscal: 'fiscalYearEnd MMDD as filed on the submissions header.',
    idForms: ['NASDAQ:AAPL', 'NYSE:<ticker>', 'CBOE:<ticker>', 'ISIN (US…)', 'LEI', 'legal name as filed', 'former name (sourced alias)'],
    auditorLine: 'Auditor: the 10-K cover inline XBRL facts, sourced to the filing URL. Transfer agent: 10-K text, labelled read by Gemini.',
    example: 'NASDAQ:AAPL', duty: 'reasonable-basis suitability (FINRA Rule 2111)'
  },
  uk: {
    country: 'United Kingdom', region: 'UK South', city: 'London', spelling: 'uk',
    title: 'United Kingdom Capital Markets Knowledge Graph — uk-cm-kg',
    meta: 'Agentic capital markets record: {{issuers}} UK issuers, {{events}} dated disclosures, every field sourced and read-dated. Served from London over MCP and A2A.',
    h1: 'Every listed company in the United Kingdom, as a record an agent can call.',
    reason: 'This node serves {{issuers}} issuer records and {{events}} dated disclosure events for the London Stock Exchange Main Market, AIM and Aquis. An agent resolves an issuer by ticker, ISIN, LEI or name; reads its record; lists the names it has traded under; pulls every disclosure since a date; and asks which of the twelve nodes holds any other market. Access is MCP (streamable-http) and A2A, five tools, answers scoped to the United Kingdom. Every field carries its source — FCA National Storage Mechanism, Companies House, LSE RNS — and the date it was read. Records are stored and served from London; the apex router holds an index and forwards, nothing more. Known gaps are stated. Market particulars, machine kit, registry entry and contact follow.',
    coverage: 'London Stock Exchange Main Market; AIM; Aquis Stock Exchange',
    sources: 'FCA National Storage Mechanism; Companies House (public profile pages, bulk data product, REST API); LSE RNS; LSE issuer profiles and instrument records (api.londonstockexchange.com); Aquis official list; GLEIF',
    mapping: 'identity (name, ticker, ISIN, segment) ← LSE instrument records and the Aquis list; company number, registered office, jurisdiction, SIC, previous names ← Companies House; LEI, other names ← GLEIF; registrar, auditor ← annual report pages (Tavily-read, canonicalised to a recognised firm list); disclosure events ← Investegate RNS, Companies House filing history, wire search',
    gaps: 'FCA National Storage Mechanism: api.data.fca.org.uk HTTP 403; UI behind a terms-of-use modal (not accepted by the machine); no per-issuer URL — the column holds the search entry URL with the LEI to search by, labelled unverified; one Gaps line per row. Listing category: the LSE issuer profile returns listingcategory: null for every issuer; the workbook carries the trading segment code instead (SET1, SET3, STMM, SSMM, SSQ3, SSX3/4, IOBE/U). Auditor names not on the recognised firm list go to Gaps.',
    gapsFrom: 'uk-width0 README, Sources table and build notes',
    tiers: 'LSE Main Market (FCA listing categories); AIM; Aquis Stock Exchange (Access, Apex).',
    language: 'English.',
    regulator: 'Financial Conduct Authority. Exchange: London Stock Exchange Group; Aquis Exchange.',
    register: 'Companies House. Register key: company number.',
    channel: 'LSE RNS; FCA National Storage Mechanism.',
    fiscal: 'set per issuer; carried as filed.',
    idForms: ['LSE:SHEL', 'SHEL.L', 'AIM:<code>', 'AQSE:<code>', 'ISIN (GB…)', 'LEI', 'legal name', 'sourced alias'],
    auditorLine: 'Auditor, registrar and going-concern note: carried from the annual report as filed.',
    example: 'LSE:SHEL', duty: 'product governance (FCA PROD sourcebook)'
  },
  fr: {
    country: 'France', region: 'France Central', city: 'Paris', spelling: 'fr',
    title: 'France Capital Markets Knowledge Graph — fr-cm-kg',
    meta: 'Agentic record of {{issuers}} French issuers on Euronext Paris and Euronext Growth keyed by ISIN, {{events}} dated disclosures from the AMF and the wires; sourced, read-dated, served from Paris over MCP and A2A.',
    h1: 'ISIN is the key in Paris: every Euronext Paris and Euronext Growth issuer as a callable record.',
    reason: 'French rosters come from the ESMA FIRDS instrument files and carry no trading symbol, so this node keys its {{issuers}} records on ISIN and accepts a symbol only as a sourced alias. {{events}} dated disclosure events sit behind them: AMF regulated information through the BDIF filer tokens, wire releases matched under the name rule, and register events by SIREN. Legal identity is the SIREN from the recherche-entreprises service and the LEI from GLEIF (registration authority RA000189), each carried with the URL and the read date. Reading is in French; Perplexity grounds, Grok reads live, Mistral translates and reviews and never writes a field. Storage and serving are in France Central; the apex router forwards, it holds no body. Lines listed in Paris under a foreign ISIN stay on this node by ruling and also resolve on their home node.',
    coverage: 'Euronext Paris (regulated market, compartments A, B, C); Euronext Growth Paris; Euronext Access Paris',
    sources: 'ESMA FIRDS instrument reference files (roster by ISIN); AMF BDIF (regulated information, filer tokens); recherche-entreprises.api.gouv.fr (SIREN, registered office, activity); GLEIF (RA000189 SIREN join, LEI records); newswires (GlobeNewswire, Business Wire, Actusnews)',
    mapping: 'identity (name, ISIN, market, compartment) ← FIRDS; SIREN, registered office, NAF code ← recherche-entreprises; LEI, other names ← GLEIF; auditor (commissaire aux comptes), registrar ← annual financial report pages (Perplexity agent low, Grok); disclosure events ← AMF BDIF per filer token, wires, register',
    gaps: 'Gaps: 496 rows — 327 issuers without a filer token, ambiguous wire hits, 168 zero-event issuers.',
    gapsFrom: 'fr-width1 README (Gaps note verbatim)',
    tiers: 'Euronext Paris compartments A (large), B (mid), C (small); Euronext Growth; Euronext Access and Access+. Compartment as carried by FIRDS where present.',
    language: 'French; English where the issuer files in English. Document titles carried as published.',
    regulator: 'Autorité des marchés financiers (AMF). Exchange operator: Euronext Paris.',
    register: 'Registre du commerce et des sociétés via INSEE / recherche-entreprises. Register key: SIREN (nine digits).',
    channel: 'AMF BDIF (information réglementée); issuer websites; newswires.',
    fiscal: 'set per issuer; most close on 31 December; carried as filed.',
    idForms: ['XPAR:FR0000120271', 'ISIN (FR…) alone', 'ALXP:<ISIN>', 'XMLI:<ISIN>', 'LEI', 'SIREN', 'legal name', 'sourced alias (symbol)'],
    auditorLine: 'Commissaires aux comptes and registrar: read from the annual financial report pages; Mistral review flags go to the Review tab, never to the field.',
    example: 'XPAR:FR0000120271', duty: 'MiFID II product governance'
  },
  nl: {
    country: 'Netherlands', region: 'West Europe', city: 'Amsterdam', spelling: 'nl',
    title: 'Netherlands Capital Markets Knowledge Graph — nl-cm-kg',
    meta: 'Agentic record of {{issuers}} Euronext Amsterdam issuers keyed by ISIN with {{events}} dated disclosures from the AFM register and the wires; sourced, read-dated, served from Amsterdam over MCP and A2A.',
    h1: 'Amsterdam by ISIN: the Euronext Amsterdam list as records an agent resolves, reads and follows.',
    reason: 'The Amsterdam roster is the FIRDS instrument file for the Euronext Amsterdam venue: ISIN, name and market, no symbol. This node holds {{issuers}} such records with {{events}} dated disclosure events, the KVK number joined through GLEIF registration authority RA000463, the LEI from GLEIF, and the AFM register pages read for the regulated-information trail. A trading symbol is accepted only when a source carried it, as an alias with that source. Dutch is the reading language; the review layer translates and flags, it does not fill. Everything is stored and served from West Europe; the apex forwards to it and holds no record. Lines with a foreign ISIN listed in Amsterdam resolve here and on their home node.',
    coverage: 'Euronext Amsterdam (regulated market)',
    sources: 'ESMA FIRDS instrument reference files (roster by ISIN); AFM registers (public register pages); GLEIF (RA000463 KVK join, LEI records); newswires (GlobeNewswire, Business Wire)',
    mapping: 'identity (name, ISIN, market) ← FIRDS; KVK number ← GLEIF registration-authority field; LEI, other names ← GLEIF; auditor, registrar ← annual report pages (Perplexity agent low, Grok); disclosure events ← AFM register pages, wires',
    gaps: 'Gaps: 1 row. KVK API and Euronext issuer pages refuse plain clients; the KVK number is carried from GLEIF only.',
    gapsFrom: 'nl-width1 README (Gaps note verbatim) and nl-width0 Sources',
    tiers: 'Euronext Amsterdam regulated market (AEX, AMX, AScX index membership not carried). Euronext Growth Amsterdam where FIRDS lists it.',
    language: 'Dutch; English for most annual reports. Titles carried as published.',
    regulator: 'Autoriteit Financiële Markten (AFM). Exchange operator: Euronext Amsterdam.',
    register: 'Kamer van Koophandel (Handelsregister). Register key: KVK number (eight digits).',
    channel: 'AFM public registers; issuer websites; newswires.',
    fiscal: 'set per issuer; carried as filed.',
    idForms: ['AMS:NL0000009165', 'XAMS:<ISIN>', 'ISIN (NL…) alone', 'LEI', 'KVK number', 'legal name', 'sourced alias (symbol)'],
    auditorLine: 'Auditor and registrar: read from the annual report pages; review flags stay on the Review tab.',
    example: 'AMS:NL0000009165', duty: 'MiFID II product governance'
  },
  ch: {
    country: 'Switzerland', region: 'Switzerland North', city: 'Zürich', spelling: 'ch',
    title: 'Switzerland Capital Markets Knowledge Graph — ch-cm-kg',
    meta: 'Agentic record of {{issuers}} SIX Swiss Exchange and BX Swiss issuers with {{events}} dated disclosures; UID from Zefix, LEI from GLEIF; sourced, read-dated, served from Zürich over MCP and A2A.',
    h1: 'SIX and BX Swiss: each Swiss listing as a sourced record with its register number attached.',
    reason: 'Switzerland is read from the SIX Swiss Exchange and BX Swiss lists, then joined to the Zefix federal register for the UID and to GLEIF for the LEI. {{issuers}} issuer records, {{events}} dated disclosure events from SIX ad hoc announcements, register changes and the wires. Foreign issuers with a SIX line — a large share of the list — carry their foreign ISIN and resolve on this node and on their home node. Reading is in German, French and Italian as filed; the review engine translates and flags. Storage and serving are in Switzerland North. The first hostnames in the estate to run under their certificates were this node\'s.',
    coverage: 'SIX Swiss Exchange (Swiss Reporting Standard, International Reporting Standard, Sparks); BX Swiss',
    sources: 'SIX Swiss Exchange issuer and instrument lists; BX Swiss list; Zefix (central business name index, UID); GLEIF; SIX ad hoc announcements; newswires',
    mapping: 'identity (name, ticker, ISIN, exchange, standard) ← SIX and BX lists; UID, seat, legal form ← Zefix; LEI, other names ← GLEIF; auditor, registrar ← annual report pages (Perplexity agent low, Grok); disclosure events ← SIX ad hoc announcements, Zefix mutations, wires',
    gaps: 'Gaps: 220 rows — 128 ambiguous wire hits (name rule), 47 issuers without a Zefix UID (no register events), 43 zero-event issuers, plus the standing notes.',
    gapsFrom: 'ch-width1 README (Gaps note verbatim)',
    tiers: 'SIX: Swiss Reporting Standard, International Reporting Standard, Standard for Investment Companies, Standard for Real Estate Companies, Sparks (SME segment); BX Swiss.',
    language: 'German, French, Italian and English as filed. Titles carried as published.',
    regulator: 'FINMA (prudential); SIX Exchange Regulation (listing rules, ad hoc publicity). Exchange operators: SIX Group; BX Swiss AG.',
    register: 'Zefix (Zentraler Firmenindex) over the cantonal commercial registers. Register key: UID (CHE-nnn.nnn.nnn).',
    channel: 'SIX ad hoc announcements; issuer websites; newswires.',
    fiscal: 'set per issuer; carried as filed.',
    idForms: ['NESN.SW', 'SIX:NESN', 'BX:<code>', 'ISIN (CH… or foreign)', 'LEI', 'UID', 'legal name', 'sourced alias'],
    auditorLine: 'Auditor (Revisionsstelle) and registrar: read from the annual report pages; unresolved reads go to the Review tab.',
    example: 'NESN.SW', duty: 'FinSA (Financial Services Act) product duties'
  },
  de: {
    country: 'Germany', region: 'Germany West Central', city: 'Frankfurt', spelling: 'de',
    title: 'Germany Capital Markets Knowledge Graph — de-cm-kg',
    meta: 'Agentic record of {{issuers}} Frankfurt and Xetra issuers with {{events}} dated disclosures and Eurex reference data on the same node; the Regulated Market versus Scale segment stays blank; served from Frankfurt over MCP and A2A.',
    h1: 'Frankfurt with the segment gap stated first: Xetra issuers, Eurex reference data, one node.',
    reason: 'The Xetra segment flag — Regulated Market (Prime Standard, General Standard) versus Scale — is not carried by any free Deutsche Börse feed, so that column is blank on every one of the {{issuers}} records here and says why. What is carried: the Xetra and Frankfurt lists, the Handelsregister number where GLEIF names it, the LEI, {{events}} dated disclosure events from ad hoc and regulatory news, the register and the wires, and — as a separate sourced door on this node — Eurex derivatives reference data (products, contracts, expirations, trading hours) read from the Deutsche Börse developer portal. No paid Deutsche Börse product is subscribed. Reading is in German; the review engine translates and flags. Storage and serving are in Germany West Central.',
    coverage: 'Frankfurt Stock Exchange / Xetra (Regulated Market and Open Market lines as listed); Eurex reference data (derivatives)',
    sources: 'Xetra and Frankfurt Stock Exchange instrument lists; GLEIF (LEI records, Handelsregister reference); Deutsche Börse developer portal, Eurex GraphQL reference data (API key, no paid feed); ad hoc and regulatory news (DGAP/EQS); newswires',
    mapping: 'identity (name, ticker, ISIN, WKN, market) ← Xetra and FWB lists; Handelsregister number and court ← GLEIF registration-authority field; LEI, other names ← GLEIF; auditor, registrar ← annual report pages (Perplexity agent low, Grok); disclosure events ← EQS ad hoc and regulatory news, register, wires; Eurex products and contracts ← Deutsche Börse developer portal',
    gaps: 'Gaps: 486 rows — 381 ambiguous hits (name rule), 103 zero-event issuers, plus the standing notes. Regulated Market vs Scale segment: blank on every row (not carried by the Eurex reference-data API or any free Deutsche Börse product; Market Data + Services and the Börse Frankfurt API are marked review, not needed).',
    gapsFrom: 'de-width1 README (Gaps note verbatim) and the Deutsche Börse standing flag',
    tiers: 'Regulated Market (Prime Standard, General Standard) and Open Market (Scale, Basic Board, Quotation Board) — the segment column is blank by stated gap; lines carried as listed.',
    language: 'German; English for many annual reports. Titles carried as published.',
    regulator: 'BaFin. Exchange operator: Deutsche Börse AG (FWB, Xetra, Eurex).',
    register: 'Handelsregister (via the registry court). Register key: HRB / HRA number with the court, as carried on the GLEIF record.',
    channel: 'EQS / DGAP ad hoc and regulatory news; Bundesanzeiger for filings; issuer websites; newswires.',
    fiscal: 'set per issuer; carried as filed.',
    idForms: ['SAP.DE', 'XETRA:SAP', 'FRA:<code>', 'EUREX:<product>', 'ISIN (DE… or foreign)', 'WKN', 'LEI', 'legal name', 'sourced alias'],
    auditorLine: 'Abschlussprüfer and registrar: read from the annual report pages; review flags to the Review tab.',
    example: 'SAP.DE', duty: 'MiFID II product governance (Produktüberwachung)'
  },
  au: {
    country: 'Australia', region: 'Australia East', city: 'Sydney', spelling: 'au',
    title: 'Australia Capital Markets Knowledge Graph — au-cm-kg',
    meta: 'Agentic record of {{issuers}} ASX and NSX issuers with {{events}} dated announcements and register events; ACN and ABN from the ASIC bulk register, LEI from GLEIF; served from Sydney over MCP and A2A.',
    h1: 'ASX and NSX, with the ASIC register alongside: Australian issuers as records with their ACN attached.',
    reason: 'Australian identity is two registers wide: the exchange list gives the listing, the ASIC company dataset on data.gov.au gives the ACN, ABN, company type, status and previous names. This node joins them for {{issuers}} issuer records and follows {{events}} dated disclosure events — ASX announcements, NSX news, ASIC register changes and the wires. Announcement PDFs on announcements.asx.com.au carry a text layer and are read for the annual report link. Addresses are blank where the ASIC bulk file carries none and the ASX record returns empty. Stored and served from Australia East; the apex only forwards.',
    coverage: 'Australian Securities Exchange (ASX); National Stock Exchange of Australia (NSX)',
    sources: 'asx.com.au directory CSV and company research API (public token); asx.com.au announcements search and announcement PDFs; NSX official-list and company-news RSS; data.gov.au ASIC Company Dataset (weekly); GLEIF',
    mapping: 'identity (name, code, ISIN, sector, listing date) ← ASX directory and research API, NSX list; ACN, ABN, type, status, previous names ← ASIC company dataset; LEI, other names ← GLEIF; auditor ← annual report link only (by order); disclosure events ← ASX announcements search, NSX RSS, ASIC register, wires',
    gaps: 'Gaps: 8,562 lines. Auditor is a source link only by order (1,874 lines). Registered office, HQ city and state are blank on 1,257 / 1,145 rows because the ASIC bulk file carries no address and the ASX company record returns empty address fields. Width 1 gaps: 67 rows — 47 asic_events: no ACN / ASIC row in Width 0 (register events cannot be read without an ACN), 20 wire hits set aside under the name rule (ambiguous match). ASIC Connect API needs a registered key (absent); TMX Australia has no machine-readable list (standing HITL).',
    gapsFrom: 'au-width0 and au-width1 READMEs (Gaps notes verbatim)',
    tiers: 'ASX (single listing tier; sector by GICS as carried by ASX); NSX. Listing date carried where the API gives it.',
    language: 'English.',
    regulator: 'Australian Securities and Investments Commission (ASIC). Exchange operators: ASX Limited; National Stock Exchange of Australia Limited.',
    register: 'ASIC company register (via the data.gov.au dataset). Register key: ACN (nine digits); ABN carried beside it.',
    channel: 'ASX Market Announcements Platform; NSX company news; ASIC register; newswires.',
    fiscal: 'set per issuer; most close on 30 June; carried as filed.',
    idForms: ['ASX:BHP', 'BHP.AX', 'NSX:<code>', 'ISIN (AU…)', 'LEI', 'ACN', 'legal name', 'previous name (sourced alias)'],
    auditorLine: 'Auditor: annual report link only, by order. Registrar: read from the ASX company record where it names one.',
    example: 'ASX:BHP', duty: 'DDO (Design and Distribution Obligations)'
  },
  sg: {
    country: 'Singapore', region: 'Southeast Asia', city: 'Singapore', spelling: 'sg',
    title: 'Singapore Capital Markets Knowledge Graph — sg-cm-kg',
    meta: 'Agentic record of {{issuers}} SGX Mainboard and Catalist issuers with {{events}} dated disclosures; UEN from ACRA via data.gov.sg, LEI from GLEIF; English filings only; served from Singapore over MCP and A2A.',
    h1: 'Mainboard and Catalist as records, with the UEN from ACRA on each: Singapore, read in English.',
    reason: 'Singapore files in English, so this node reads every filing it can reach without translation. {{issuers}} issuer records from the SGX securities and market-metadata feeds, joined to the ACRA entity data published on data.gov.sg for the UEN and to GLEIF (registration authority RA000523) for the LEI; {{events}} dated disclosure events from company announcements reached through the wires and register changes. The SGX announcements and companies endpoints refuse machines, so the announcement trail is read from the wires and the register, not from SGXNet. Trust and REIT lines are named by their trading name as SGX lists them. Stored and served from Southeast Asia.',
    coverage: 'Singapore Exchange Mainboard; SGX Catalist',
    sources: 'SGX securities, market-metadata and stock-screener feeds; ACRA entity data via data.gov.sg (collection 2); GLEIF (RA000523 UEN join, LEI records); newswires',
    mapping: 'identity (name, code, ISIN, board, sector) ← SGX feeds; UEN, entity type, status ← ACRA data.gov.sg; LEI, other names ← GLEIF; auditor ← annual report pages (ACRA audit-firm columns are empty); disclosure events ← wire releases, ACRA register changes',
    gaps: 'Gaps: 409 rows — 308 wire hits set aside under the name rule (ambiguous match), 87 issuers with no UEN (no ACRA register events), 11 zero-event issuers, and the three standing notes (SGXNet API, ACRA dates, IR pages).',
    gapsFrom: 'sg-width1 README (Gaps note verbatim)',
    tiers: 'SGX Mainboard; Catalist (sponsor-supervised). Board as carried by the SGX feed.',
    language: 'English.',
    regulator: 'Monetary Authority of Singapore (MAS); SGX RegCo (listing rules). Exchange operator: Singapore Exchange Limited.',
    register: 'ACRA (Accounting and Corporate Regulatory Authority). Register key: UEN (Unique Entity Number).',
    channel: 'SGXNet company announcements (refuses machines; read via the wires); ACRA register; newswires.',
    fiscal: 'set per issuer; carried as filed.',
    idForms: ['D05.SI', 'SGX:D05', 'SGX-CATALIST:<code>', 'ISIN (SG…)', 'LEI', 'UEN', 'legal name', 'trading name (sourced alias)'],
    auditorLine: 'Auditor: read from the annual report pages; ACRA audit-firm columns are empty in the published dataset.',
    example: 'D05.SI', duty: 'MAS product due diligence'
  },
  jp: {
    country: 'Japan', region: 'Japan East', city: 'Tokyo', spelling: 'jp',
    title: 'Japan Capital Markets Knowledge Graph — jp-cm-kg',
    meta: 'Agentic record of {{issuers}} Tokyo Stock Exchange issuers (Prime, Standard, Growth, PRO Market, REITs) with {{events}} dated EDINET filings carried in Japanese; served from Tokyo over MCP and A2A.',
    h1: 'Filings carried in Japanese: every TSE issuer with its EDINET code and corporate number, as a record.',
    reason: 'Japan is read in Japanese and carried in Japanese: document titles from EDINET are never translated on this node. {{issuers}} issuer records from the JPX listed-issuer file joined to the EDINET code list for the EDINET code and the 13-digit corporate number, and to the GLEIF golden copy (registration authority RA000412) for the LEI. {{events}} dated disclosure events from the EDINET daily document lists — securities reports, quarterly reports, extraordinary reports, large-holding reports — each with its document ID and viewer link. The auditor and fiscal year end are the tagged facts in the EDINET XBRL-CSV of the securities report, not a reading of the PDF. PRO Market lines carry no EDINET filer and say so. Stored and served from Japan East.',
    coverage: 'Tokyo Stock Exchange Prime, Standard, Growth; TOKYO PRO Market; listed REITs (J-REIT)',
    sources: 'JPX listed issuers file (data_e.xlsx); EDINET code list (Edinetcode.zip); EDINET API v2 (daily document lists, PDF and XBRL-CSV per document); GLEIF golden copy (RA000412 corporate-number join, LEI records, ISIN mapping)',
    mapping: 'identity (code, name, market segment, sector) ← JPX file; EDINET code, corporate number, filer name ← EDINET code list; LEI ← GLEIF golden copy joined on the corporate number; auditor (jpcrp_cor:AuditFirm1Consolidated), fiscal year end (jpdei_cor:CurrentFiscalYearEndDateDEI) ← EDINET XBRL-CSV; disclosure events ← EDINET daily document lists (type 2)',
    gaps: 'PRO Market: 187 lines carry no EDINET filer (no filings on this node for them). Going-concern notes are carried only from notes named GoingConcern in the XBRL; boilerplate is not read as a note. Equity ISINs come only from the GLEIF mapping (pattern JP3…00x is checked, never derived). Titles in Japanese as published; no translation.',
    gapsFrom: 'jp-width0 / jp-fill-confirm READMEs and the ORDER-017 build log',
    tiers: 'Prime; Standard; Growth; TOKYO PRO Market (professional investors); REIT section. Segment as carried by the JPX file.',
    language: 'Japanese. Document titles carried as published (有価証券報告書, 四半期報告書, 臨時報告書, 大量保有報告書); English company names as published by JPX.',
    regulator: 'Financial Services Agency (金融庁); Kanto Local Finance Bureau for EDINET filings. Exchange operator: Japan Exchange Group (Tokyo Stock Exchange).',
    register: 'National Tax Agency corporate number (法人番号, 13 digits) as carried on the EDINET code list; Legal Affairs Bureau commercial registry behind it. Register key: corporate number.',
    channel: 'EDINET (statutory disclosure); TDnet (timely disclosure, not read on this node).',
    fiscal: 'set per issuer; most close on 31 March; carried from the XBRL fact.',
    idForms: ['7203.T', 'TSE-PRIME:7203', 'TSE-STANDARD:<code>', 'TSE-GROWTH:<code>', 'securities code alone', 'ISIN (JP3…)', 'LEI', 'EDINET code', 'legal name (Japanese or English as published)'],
    auditorLine: 'Auditor: the AuditFirm1Consolidated fact of the securities report XBRL, sourced to the EDINET document. Transfer agent (株主名簿管理人): read by Gemini from the securities report text.',
    example: '7203.T', duty: 'suitability principle (FIEA Article 40)'
  },
  kr: {
    country: 'South Korea', region: 'Korea Central', city: 'Seoul', spelling: 'kr',
    title: 'South Korea Capital Markets Knowledge Graph — kr-cm-kg',
    meta: 'Agentic record of {{issuers}} KOSPI, KOSDAQ and KONEX issuers with {{events}} dated DART filings carried in Korean; auditor and opinion from the DART structured endpoint; served from Seoul over MCP and A2A.',
    h1: 'DART first: every KRX issuer with its DART corporation code, filings in Korean, auditor and opinion as structured facts.',
    reason: 'Korea is built on DART, the FSS electronic disclosure system: the corporation code list gives the DART code per issuer, the filing list per code gives {{events}} dated disclosure events over the trailing twelve months, and the auditor endpoint gives the audit firm, its opinion and the settlement date as structured fields rather than a reading. {{issuers}} issuer records come from the KIND download of the KRX list (KOSPI, KOSDAQ, KONEX), the business registration number joined to GLEIF (registration authority RA000657) for the LEI. Report names are carried in Korean as published and typed by name. Forty-three KIND lines share a code with another line and are flagged, not merged. DART is capped at 20,000 calls a day, so sweeps are paced. Stored and served from Korea Central.',
    coverage: 'KOSPI (유가증권시장); KOSDAQ; KONEX',
    sources: 'KIND corpList download (KRX listed corporations); DART corpCode.xml, company.json, list.json per corporation code, accnutAdtorNmNdAdtOpinion.json (auditor, opinion, settlement date), document.xml; GLEIF golden copy (RA000657 business-registration join, LEI records, ISIN mapping)',
    mapping: 'identity (code, name, market) ← KIND corpList; DART corporation code, business registration number, corporate registration number, address, fiscal month ← DART company.json; LEI ← GLEIF golden copy joined on the business registration number; auditor, audit opinion, settlement date ← DART auditor endpoint; disclosure events ← DART list.json per corporation code, typed by report name',
    gaps: '43 KIND lines share a code with another line (flagged, not merged). Report types are taken from the report name because list.json carries no pblntf_ty in its response. Equity ISINs come only from the GLEIF mapping (pattern KR7…00x is checked, never derived). Titles in Korean as published; no translation. DART daily cap 20,000 calls.',
    gapsFrom: 'kr-width0 / kr-fill-confirm READMEs and the ORDER-017 build log',
    tiers: 'KOSPI (main board); KOSDAQ (growth board); KONEX (start-up board). Market as carried by KIND (유가 = KOSPI).',
    language: 'Korean. Report names carried as published (사업보고서, 분기보고서, 주요사항보고서, 임원ㆍ주요주주특정증권등소유상황보고서).',
    regulator: 'Financial Services Commission and Financial Supervisory Service (DART operator). Exchange operator: Korea Exchange (KRX).',
    register: 'Supreme Court corporate registry; business registration with the National Tax Service. Register key: business registration number (사업자등록번호, XXX-XX-XXXXX); corporate registration number carried beside it.',
    channel: 'DART (전자공시시스템); KIND (KRX disclosure, roster only on this node).',
    fiscal: 'settlement month as carried by DART (most 12); settlement date from the auditor endpoint.',
    idForms: ['005930.KS', 'KOSPI:005930', 'KOSDAQ:<code>', 'KONEX:<code>', 'securities code alone', 'ISIN (KR7…)', 'LEI', 'DART corporation code', 'business registration number', 'legal name (Korean or English as published)'],
    auditorLine: 'Auditor, audit opinion and settlement date: the DART structured endpoint, sourced to the DART API call. Transfer agent (명의개서대리인): read by Gemini from the business report text.',
    example: '005930.KS', duty: 'suitability and appropriateness (FSCMA Articles 46 and 46-2)'
  },
  hk: {
    country: 'Hong Kong', region: 'East Asia (configuration line only)', city: 'Hong Kong', spelling: 'hk', partner: true,
    title: 'Hong Kong Capital Markets Knowledge Graph — hk-cm-kg',
    meta: 'Hong Kong node of the Capital Markets Knowledge Graph held at Width 0: {{issuers}} HKEX Main Board, GEM and REIT lines with identifiers in English, no door, no filings read. Local partner wanted.',
    h1: 'Local partner wanted: Hong Kong is held at Width 0 — roster and identifiers in English, no door until a partner reads the filings.',
    reason: 'Hong Kong is the one node in the twelve without a door. By order it stops at Width 0: the HKEX list of securities (Main Board, GEM, REITs), {{issuers}} lines with stock code, ISIN, name in English and the LEI where the GLEIF mapping carries it. No search layer, no filings read, no Fill pass, no events, no MCP endpoint, no Agent Card. Width 1 (HKEXnews disclosures in Chinese and English), the Fill pass (auditor, registrar, going concern from the annual report) and the door wait for a local partner who reads the filings in the language they are filed in and stands behind the reading. This page states what is held and what is wanted; it answers nothing itself and there is no endpoint to hand a caller to. Enquiries go to the contact of record in clause 9.',
    coverage: 'HKEX Main Board; GEM; listed REITs — roster only (Width 0)',
    sources: 'HKEX list of securities (xlsx); GLEIF ISIN-to-LEI mapping and LEI records',
    mapping: 'identity (stock code, name in English, ISIN, board) ← HKEX list; LEI, legal jurisdiction, other names ← GLEIF; no other field class is populated at Width 0',
    gaps: 'Width 0 only by order: no Width 1, no Fill, no door. Chinese names are not carried (English list only). Filings on HKEXnews are not read. No events. Everything past the roster waits for a local partner.',
    gapsFrom: 'hk-width0 README and the ORDER-017 re-cut',
    tiers: 'Main Board; GEM; REITs — as carried by the HKEX list of securities. Not populated beyond the roster.',
    language: 'English list only at Width 0. Filings are in Chinese and English on HKEXnews; not read.',
    regulator: 'Securities and Futures Commission (SFC). Exchange operator: Hong Kong Exchanges and Clearing Limited.',
    register: 'Companies Registry. Register key: company number (CR number) — not populated at Width 0.',
    channel: 'HKEXnews (not read on this node).',
    fiscal: 'not carried at Width 0.',
    idForms: ['none — no door on this node; the roster is not served'],
    auditorLine: 'Not populated at Width 0.',
    example: null, duty: 'suitability (SFC Code of Conduct paragraph 5.2)'
  }
};
