// ORDER-020 §7 — Agentic RADAR widget index v1: fourteen widgets, each bound to a door, a log or a ledger; nothing quoted from a third party.
// Sources: list_nodes (01, 03, 07), the §6 probe in KV (02), numbers-log.json (03, 06), calls.json (04, 05 — the Workers analytics rail), the registry API (09),
// spend.json (12, as reported), filings.json (09). A widget whose source is not readable says so and shows no number.
import { APEX, APEX_AGENT, CONTACT, CONTACT2, REGION_FULL, REGIONS_LIST, esc, int, num, table, form } from './chrome.js';
const REGIONS = REGIONS_LIST.split(' · ');
import { ORDER, nodesTable, tiles, totals } from './products.js';
import { statusRows } from './site.js';

async function asset(env, origin, name) { try { const r = await env.ASSETS.fetch(new Request(origin + '/' + name)); return r.ok ? await r.json() : null; } catch (e) { return null; } }
let REG = null, REG_AT = 0;
async function registry() {
  if (REG && Date.now() - REG_AT < 600000) return REG;
  try { const j = await fetch('https://registry.modelcontextprotocol.io/v0.1/servers/io.github.allooloo%2Fcm-kg/versions', { signal: AbortSignal.timeout(15000) }).then(r => r.json()); const vs = (j.servers || []).map(s => ({ version: s.server.version, latest: !!(s._meta && s._meta['io.modelcontextprotocol.registry/official'] && s._meta['io.modelcontextprotocol.registry/official'].isLatest) })); REG = { versions: vs, latest: (vs.find(v => v.latest) || {}).version || null }; REG_AT = Date.now(); } catch (e) { REG = REG || { versions: [], latest: null, error: 'registry did not answer at render' }; }
  return REG;
}
const W = (n, title, srcline, inner) => `<h2><code>${String(n).padStart(2, '0')}</code> ${esc(title)}</h2>${inner}<p class="src">source: ${srcline}</p>`;
const bars = arr => arr && arr.length ? `<div class="bars">${arr.map(v => `<i style="height:${Math.max(2, Math.min(40, Math.round(40 * v / Math.max(1, Math.max(...arr)))))}px" title="${v}"></i>`).join('')}</div>` : '<p class="muted">no series yet</p>';

export async function radarData(ctx, env, origin, st) {
  const [log, calls, spend, filings, reg] = await Promise.all([asset(env, origin, 'numbers-log.json'), asset(env, origin, 'calls.json'), asset(env, origin, 'spend.json'), asset(env, origin, 'filings.json'), registry()]);
  const t = totals(ctx); const rows = statusRows(ctx, st);
  const perNode = ORDER.map(cc => { const n = ctx.live[`${cc}-cm-kg`] || {}; const d = ctx.nodes[cc]; return { node: `${cc}-cm-kg`, market: d.country, region: d.region, live: !!n.live, records: n.live ? n.records : null, events: n.live ? n.events : null, issuers_with_events: n.live ? n.issuers_with_events : null, drop: n.live ? n.as_of : null, gaps_note: d.gaps }; });
  return { as_of: new Date().toISOString(), version: 'v1.0', operator: 'Allooloo Technologies Corp.',
    record: { issuers: t.records, events: t.events, nodes_live: t.nodes, last_drop: t.last, per_node: perNode, source: 'list_nodes' },
    doors: { probe: 'resolve_issuer every five minutes', nodes: rows.map(r => { const { bars, ...rest } = r; return rest; }), source: 'estate Worker cron → KV' },
    trail: { per_node: perNode.map(n => ({ node: n.node, events_ttm: n.events })), numbers_log: log, source: 'list_nodes; NODE-SURFACES.md NUMBERS LOG' },
    calls: calls || { note: 'calls.json not yet written by the analytics rail', source: 'Cloudflare Workers analytics (GraphQL) via RAILS\\calls_analytics.py' },
    geography: (calls && calls.geography) || { note: 'calls by region need Zone Analytics Read on the token of record — HITL; not shown', source: 'Cloudflare zone analytics (not readable)' },
    motion: { numbers_log: log, source: 'NUMBERS LOG lines (one per sweep per node)' },
    provenance: { rule: 'every field served carries source_url, read_by and state; the door renders no field without source and read date (by construction of the record shape)', fields_with_source_and_read_date: '100% by construction', per_node_gaps: perNode.map(n => ({ node: n.node, gaps_note: n.gaps_note })), source: 'door record shape; rail README Gaps notes' },
    residency: { regions: ORDER.map(cc => ({ node: `${cc}-cm-kg`, region: REGION_FULL[cc], in_country: cc !== 'hk' })), apex: 'index only, forwards', no_fallback: true, source: 'AZURE\\provision_region.py; apex router' },
    registry: { mcp_registry: reg, agent_cards: ORDER.filter(cc => cc !== 'hk').length + 1, filings: filings || { note: 'filings.json not written' }, source: 'registry.modelcontextprotocol.io; filings.json (as reported)' },
    machine_surfaces: ['https://agentic-radar.ai/radar.json', 'https://allooloo.io/status.json', 'https://allooloo.io/llms.txt', 'https://allooloo.io/facts.json', `${APEX_AGENT}/.well-known/agent-card.json`, `${APEX}/openapi.json`, `${APEX}/mcp.json`, 'https://agentic-radar.ai/sitemap.xml'],
    spend: spend || { note: 'spend.json not written' }, broadcast: { x: '@allooloo_io', mail: CONTACT2 }, contact: CONTACT };
}

export function radarBody(ctx, host, d) {
  const perNode = d.record.per_node;
  const w01 = W(1, 'The Record', 'list_nodes at ' + esc(APEX) + '/mcp, read at render', `${tiles(ctx)}${nodesTable(ctx)}`);
  const w02 = W(2, 'The Doors', 'the §6 probe (estate Worker cron, every five minutes) → KV; allooloo.io/status', `<div class="wrap">${table(['node', 'region', 'state', 'response ms', '24h median', 'samples'], d.doors.nodes.map(r => [`<code>${r.node}</code>`, esc(r.region), r.state === 'up' ? '<span class="pill live">up</span>' : `<span class="pill">${esc(r.state)}</span>`, `<span class="n">${r.ms == null ? '—' : r.ms}</span>`, `<span class="n">${r.median_24h == null ? '—' : r.median_24h}</span>`, `<span class="n">${r.samples}</span>`]))}</div>`);
  const logLines = (d.trail.numbers_log && d.trail.numbers_log.lines) || [];
  const w03 = W(3, 'The Trail', 'list_nodes (events, trailing twelve months); NUMBERS LOG (weekly delta)', `<div class="wrap">${table(['node', 'events (ttm)', 'issuers with events', 'drop'], perNode.map(n => [`<code>${n.node}</code>`, `<span class="n">${n.events == null ? '—' : int(n.events)}</span>`, `<span class="n">${n.issuers_with_events == null ? '—' : int(n.issuers_with_events)}</span>`, esc(n.drop || (n.node === 'hk-cm-kg' ? 'Width 0' : ''))]))}</div><p class="muted">weekly delta line: ${logLines.length} Numbers Log lines (${logLines.filter(l => /events [+-]/.test(l.note || '')).length} with a delta)</p>`);
  const c = d.calls; const series = c && c.daily ? c.daily : null;
  const w04 = W(4, 'Calls', c && c.source ? esc(c.source) : 'Cloudflare Workers analytics via the calls rail', series ? `<div class="wrap">${table(['day', 'apex calls', 'estate surface calls'], series.map(x => [esc(x.day), `<span class="n">${int(x.apex)}</span>`, `<span class="n">${int(x.estate)}</span>`]))}</div><p class="muted">tool mix and markets asked: ${c.tool_mix ? esc(JSON.stringify(c.tool_mix)) : 'not logged at the apex today (no request body logging by design)'}. Per regional door: ${c.per_door_note ? esc(c.per_door_note) : 'not readable — zone analytics needs Zone Analytics Read (HITL)'}</p>` : `<p class="muted">${esc((c && c.note) || 'no series')}</p>`);
  const g = d.geography;
  const w05 = W(5, 'Geography', g && g.source ? esc(g.source) : 'Cloudflare zone analytics', g && g.by_region ? `<div class="wrap">${table(['region', 'calls %'], g.by_region.map(x => [esc(x.region), `<span class="n">${x.pct}</span>`]))}</div>` : `<p class="muted">${esc((g && g.note) || 'not readable')}</p>`);
  const w06 = W(6, 'Motion', 'NUMBERS LOG — one line per sweep per node (NODE-SURFACES.md §9); mirrored as numbers-log.json', logLines.length ? `<div class="wrap">${table(['node', 'drop', 'records', 'events', 'delta'], logLines.slice(-24).map(l => [`<code>${esc(l.node)}</code>`, esc(l.date), `<span class="n">${esc(l.records)}</span>`, `<span class="n">${esc(l.events)}</span>`, esc(l.note)]))}</div>` : '<p class="muted">no lines yet</p>');
  const w07 = W(7, 'Provenance', 'the record shape on every door (no field without source_url + read_by); rail README Gaps notes per node', `${num(7, ['Fields with source and read date: 100% by construction — the door renders a field only with <code>source_url</code>, <code>read_by</code> and <code>state</code>.', 'States: <code>sourced</code> (registry, list or tag) · <code>filled</code> (engine read) · <code>confirmed</code> (read at the source of record). "Signed" is reserved for CMR signing, not in service.'])}<div class="wrap">${table(['node', 'known gaps (from the rail README)'], perNode.map(n => [`<code>${n.node}</code>`, esc(n.gaps_note)]))}</div>`);
  const w08 = W(8, 'Residency', 'AZURE\\provision_region.py (one storage account and one door per region); apex router index only', `<div class="wrap">${table(['node', 'region', 'in-country'], d.residency.regions.map(r => [`<code>${r.node}</code>`, esc(r.region), r.in_country ? 'yes' : 'beacon only']))}</div><p>Apex: index only, forwards to the owning node; no record body leaves its jurisdiction; no fallback across borders. Eleven regions: ${REGIONS.join(' · ')}.</p>`);
  const reg = d.registry.mcp_registry; const fl = d.registry.filings;
  const w09 = W(9, 'Registry', 'registry.modelcontextprotocol.io (read at render); Agent Cards on the doors; filings.json (as reported)', `${num(9, [`MCP registry card <code>io.github.allooloo/cm-kg</code>: latest version <code>${esc(reg.latest || 'not read')}</code> (${reg.versions.length} versions published${reg.error ? '; ' + esc(reg.error) : ''}).`, `Agent Cards published: ${d.registry.agent_cards} (eleven node agents + the apex agent), each at <code>agent.&lt;host&gt;/.well-known/agent-card.json</code>.`, 'Skill state: registration skill not yet in service (Registries gate).'])}${fl && fl.filings ? `<div class="wrap">${table(['registry', 'state', 'as of'], fl.filings.map(f => [esc(f.registry), esc(f.state), esc(f.as_of)]))}</div>` : ''}`);
  const w10 = W(10, 'Machine surfaces', 'each URL listed answers at render or is listed as it is', num(10, d.machine_surfaces.map(u => `<a href="${u}"><code>${esc(u)}</code></a>`)));
  const w11 = W(11, 'Cite · Embed', 'this page and radar.json — free, no registration', `${num(11, ['Citation: <code>Allooloo Technologies Corp., Agentic RADAR — the estate numbers, https://agentic-radar.ai/, as of ' + esc(d.as_of.slice(0, 10)) + ', radar.json v1.0.</code>', 'GET: <pre>curl -s https://agentic-radar.ai/radar.json | jq .record</pre>', 'Embed: <pre>&lt;iframe src="https://agentic-radar.ai/" title="Agentic RADAR" width="100%" height="900" loading="lazy"&gt;&lt;/iframe&gt;</pre> (frame-ancestors is none on every other Allooloo surface; this page carries its own policy for the embed)', 'Export: <a href="/radar.json"><code>/radar.json</code></a> · <a href="/radar.csv"><code>/radar.csv</code></a> (per-node record and trail counts).'])}`);
  const sp = d.spend;
  const w12 = W(12, 'Spend', 'spend.json — the standing spend line, as reported per order and per sweep; Azure from the Cost Management API when it answers', sp && sp.lines ? `<div class="wrap">${table(['line', 'node', 'figure', 'as of'], sp.lines.map(l => [esc(l.line), esc(l.node || ''), esc(l.figure), esc(l.as_of)]))}</div><p class="muted">${esc(sp.note || '')}</p>` : `<p class="muted">${esc((sp && sp.note) || 'no spend lines')}</p>`);
  const w13 = W(13, 'Broadcast', 'the operator', num(13, ['<a href="https://x.com/allooloo_io">@allooloo_io</a>', `<a href="mailto:${CONTACT2}">${CONTACT2}</a> — the agents that built this read their own mail`]));
  const w14 = W(14, 'Contact Us', 'the form (Formspree) — the only support door', form(host));
  return `<p class="kicker">AGENTIC RADAR · The estate numbers · Allooloo Technologies Corp. · v1.0 · rendered ${esc(d.as_of.replace('T', ' ').slice(0, 19))} UTC</p>
<p class="lead">Every figure on this page is a door, a log or a ledger; nothing is quoted from a third party. Machine twin: <a href="/radar.json"><code>/radar.json</code></a>.</p>${w01}${w02}${w03}${w04}${w05}${w06}${w07}${w08}${w09}${w10}${w11}${w12}${w13}${w14}`;
}
export function radarCsv(d) { return 'node,market,region,live,records,events,issuers_with_events,drop\n' + d.record.per_node.map(n => [n.node, n.market, n.region, n.live, n.records ?? '', n.events ?? '', n.issuers_with_events ?? '', n.drop ?? ''].join(',')).join('\n') + '\n'; }
