CREATE TABLE IF NOT EXISTS records (cmr TEXT PRIMARY KEY, node TEXT NOT NULL, exchange TEXT NOT NULL, ticker TEXT NOT NULL, name TEXT, isin TEXT, lei TEXT, as_of TEXT, version INTEGER, json TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS records_node ON records (node);
CREATE TABLE IF NOT EXISTS events (id INTEGER PRIMARY KEY AUTOINCREMENT, cmr TEXT NOT NULL, date TEXT, json TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS events_cmr_date ON events (cmr, date);
CREATE TABLE IF NOT EXISTS idx (kind TEXT NOT NULL, value TEXT NOT NULL, cmr TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_kind_value ON idx (kind, value);
CREATE INDEX IF NOT EXISTS idx_cmr ON idx (cmr);
CREATE TABLE IF NOT EXISTS meta (k TEXT PRIMARY KEY, json TEXT NOT NULL);
