name = "estate-pages"
main = "worker/surfaces.js"
compatibility_date = "2026-09-01"
workers_dev = false
preview_urls = false

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[observability]
enabled = true

[[kv_namespaces]]
binding = "STATUS"
id = "c651588272f14f3080c7dd99be21a4fd"

[triggers]
crons = ["*/5 * * * *"]
